services:
  eventscraper:
    container_name: eventsc
    build: .
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
    security_opt:
      - no-new-privileges:true
    env_file: docker.env
    networks:
        - cteventscraper
    volumes:
      - /home/zek/Docker-Data/CTEventScraper:/app/config:z

networks:
    cteventscraper:
